apiVersion: v1
kind: Service
metadata:
  name: {{ template "web.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "web.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
{{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
    nodePort: {{ .Values.service.nodePort }}
{{- end }}
  selector:
    {{- include "web.labels" . | indent 4 }}